DROP DATABASE IF EXISTS zoo;

CREATE DATABASE IF NOT EXISTS zoo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE zoo;

DROP TABLE IF EXISTS chat;

CREATE TABLE IF NOT EXISTS chat (
    id INT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    yeux VARCHAR(50) NOT NULL,
    age INT NOT NULL
);
